# Nome da Aplicação
spring.application.name=cinehub

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (SUPABASE)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rlbtqqhuceebtowrvsvk
# A senha será lida das variáveis de ambiente do Render por segurança
spring.datasource.password=${DB_PASSWORD}

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURAÇÕES DA API DO TMDB
# ==========================================
tmdb.api.url=https://api.themoviedb.org/3
# As chaves serão lidas das variáveis de ambiente do Render por segurança
tmdb.api.token=${TMDB_API_TOKEN}
tmdb.api.key=${TMDB_API_KEY}

# ==========================================
# CONFIGURAÇÕES DO SERVIDOR (RENDER)
# ==========================================
# Diz ao Spring para usar a porta que o Render definir, ou 8080 se estiver rodando local no seu PC
server.port=${PORT:8080}