spring.application.name=cinehub

# Configurações de conexão com o banco de dados (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rlbtqqhuceebtowrvsvk
# Aqui dizemos ao Spring: "Busque o valor da variável DB_PASSWORD"
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração da API do TMDB
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.token=${TMDB_API_TOKEN}
tmdb.api.key=${TMDB_API_KEY}