name: Keep Alive Cinehub
on:
  schedule:
    - cron: '*/10 * * * *' # Executa a cada 10 minutos
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Acorda Servidor
        run: curl -I https://cinehub-fqcc.onrender.com
